/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sn_trader_TradexCpp */

#ifndef _Included_com_sn_trader_TradexCpp
#define _Included_com_sn_trader_TradexCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sn_trader_TradexCpp
 * Method:    doLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sn_trader_TradexCpp_doLogin
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_sn_trader_TradexCpp
 * Method:    placeOrder
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sn_trader_TradexCpp_placeOrder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
